# Nome da Pipeline
name: N1-Execucao-Manual

# Sem gatilho automático
trigger: none

# Sem Pull Request automático
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:

# Checkout do código
- checkout: self

# Instalação do Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '24.x'
  displayName: 'Instalando Node.js'

# Instalação do Yarn
- script: |
    npm install -g yarn
  displayName: 'Instalando Yarn'

# Instalação das dependências
- script: |
    yarn
  displayName: 'Instalando Dependências'

# Instalação dos browsers do Playwright
- script: |
    yarn playwright install
  displayName: 'Instalando Browsers do Playwright'

# Execução dos testes E2E
- script: |
    yarn run e2e
  displayName: 'Executando Testes E2E'

# Publicação dos relatórios
- task: PublishPipelineArtifact@1
  condition: always()
  inputs:
    targetPath: 'playwright-report'
    artifact: 'Relatorio-Testes-E2E'
  displayName: 'Salvando Relatórios de Teste'
